### ISSUE TITLE
Add Greek letters in plots

### ISSUE THREAD

**Issue by VeroIarrachtai** [VeroIarrachtai/Abies_religiosa_vs_ozone#14]
###################################################
After I obtained that data, I made a barplot with the amounts of metabolites calculated in this [script](https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/METABOLOMICS/bin/Rstudio/Metabolitos.TV1.R ), which is in:
`VeroIarrachtai / Abies_religiosa_vs_ozone / METABOLOMICS / bin / Rstudio / Metabolitos.TV1.R`

This script should be optimized with a for loop. However, now I want  to add [Greek letters and the names of my treatments](https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/wonderful_images/MetaBarplot-IW.png).

###################################################
## You can help me in:

1.- Plot my image with the Greek letters and the names of my treatments.

I [did](https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/wonderful_images/Metabolites_barplot-IH.png)
I [want](https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/wonderful_images/MetaBarplot-IW.png).

**Comment by almamelisa** [comment]
Hi Vero, 

With the function scale_x_discrete you can change the x labels names, and use the expression function to add the greek characters with ~ you can add regular text to the greek letter.
Like this:   


`p <- ggplot(df_mean, aes(metabolito, value)) + geom_bar(aes(fill = Factores), stat="identity") + 
  facet_wrap(~Factores, ncol=1) + geom_errorbar(limits, position="dodge") 
pg<-p + scale_x_discrete (labels = c('beta.pinene' = expression(beta~'.pine'), 
                                      'L.alfa.bornyl.acetate' = expression('L.'~alpha~'.bornyl.acetate'),
                                      'beta.Caryophyllene.oxide'= expression(beta~'.Caryophyllene.oxide'),
                                      'alfa.Caryophyllene' = expression(alpha~'.Caryophyllene'),
                                      'beta.Cubebene'= expression(beta~'.Cubebene'),
                                     'alfa.Cubenene'= expression(alpha~'.Cubenene'),
                                     'delta.Cadinene' = expression(delta~'.Cadinene'),
                          'alfa.Muurolene' = expression(alpha~'.Muurolene')))

plot(pg)
                                         
pg + coord_flip() + facet_wrap(~ Factores)+ 
  scale_fill_manual(breaks = c("Concentración moderada Dañada 2015", "Concentración moderada Dañada 2016",
                               "Concentración moderada Sana 2015", "Concentración moderada Sana 2016"),
                    values= c( "#c6003a", "#e98382", `"#00901e","#b1e787"))`

**Comment by VeroIarrachtai** [comment]
Thanks a lot Melisa !!!!

I can change the letters in my (barplot with Greek letters)[https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/wonderful_images/Metabolites_barplot_greek_letters_WIN.png]

I add "~" before alpha to add "L- (o r others characters before greek letter)"
`'L.alfa.bornyl.acetate'` = expression('L-'~ alpha ~'-Acetato de Bornilo')`

The final code to change add greek letters in my (barplot)[https://github.com/VeroIarrachtai/Abies_religiosa_vs_ozone/blob/master/wonderful_images/Metabolites_barplot_greek_letters_WIN.png] is:
`
p <- ggplot(df_mean, aes(metabolito, value, fill = Factores)) + 
  geom_bar(position="dodge", stat="identity") + geom_errorbar(limits, position="dodge")
p + coord_flip() + facet_wrap(~ Factores) + 
  scale_fill_manual(breaks = c("Concentración moderada Dañada 2015", "Concentración moderada Dañada 2016", "Concentración moderada Sana 2015", "Concentración moderada Sana 2016"),
                    values= c( "#c6003a", "#e98382", "#00901e","#b1e787"))+ 
  scale_x_discrete (labels = c('beta.pinene' = expression(beta~'-Pineno'),
                               'L.alfa.bornyl.acetate' = expression('L-'~ alpha ~'-Acetato de Bornilo'),
                               'beta.Caryophyllene.oxide'= expression(beta~'-Óxido de Cariofileno'),
                               'alfa.Caryophyllene' = expression(alpha~'-Cariofileno'),
                               'beta.Cubebene'= expression(beta~'-Cubebeno'),
                               'alfa.Cubenene'= expression(alpha~'-Cubeneno'),
                               'delta.Cadinene' = expression(delta~'-Cadineno'),
                               'alfa.Muurolene' = expression(alpha~'-Muuroleno')))
`
