### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by Rodolfo47** [VeroIarrachtai/Abies_religiosa_vs_ozone#17]
Hi Vero,

I’m not sure if this info are informative for other people “This repository contains all the scripts of my Master's Thesis project”

Your general README.md are so cute…
but I thing the last part (Each one of these directories have inside:) are redundant

You must up date your methodological seminar, I see the your project presentation in the info directory, but I’m not sure that in the abstract file you discuss your current results or problems…

I suggest do not split the /GENOMICS/ scrips in 2 subdirectories, also I suggest to numerate them. Currently you have a bit messy this section.
I think in data there must be the sequencing data, and in meta other kind of data like some of this tables

I can not find any R plot, do not forget the [evaluation criteria](https://github.com/AliciaMstt/TallerBioinf/blob/master/Unidad4/Unidad4_proyectobioinf.md)

pleas try to solve this issues
cheers ;)

**Comment by Rodolfo47** [comment]
why do you have .html files in your Transcriptome/bin dir?

**Comment by VeroIarrachtai** [comment]
Hi Rodolfo

I followed the advice to avoid redundancy. Delete folders that could be confusing to other users.
I still don't upload my methodological seminar. I hope to have it available on Nov. 20 at midnight. The summary file is a summary of my work from which this repository emerged. My current problems with my texts are in the issues.

I have numbered my scripts and written a README that I hope will clarify how to analyze genomic, transcriptomic and metabolomic data as I did for my project.

The graphs in R product of the scripts are in the outputs folder of each section.

Thanks for the comments. I hope I have responded in the best way to your observations

Cheers

**Comment by VeroIarrachtai** [comment]
> why do you have .html files in your Transcriptome/bin dir?

Because I like to generate an html file (markdown) when I check that my scripts run well in Rstudio. However, once I verify that they run properly I will delete them from the directories.

**Comment by Rodolfo47** [comment]
Hi Vero,

I see you have update the README.md, upload your meth. seminar and I see the r plots
Fine, thats all
